apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lamassu-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca-cert
  namespace: default
spec:
  isCA: true
  commonName: lamassu-ca
  secretName: root-ca-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: lamassu-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lamassu-ca-issuer
  namespace: default
spec:
  ca:
    secretName: root-ca-cert-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lamassu-downstream-cert
  namespace: default
spec:
  isCA: false
  commonName: dev.lamassu.io
  secretName: downstream-crt-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - "*.dev.lamassu.io"
    - "dev.lamassu.io"
  issuerRef:
    name: lamassu-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
