apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lamassu-db-cert
  namespace: default
spec:
  isCA: false
  commonName: lamassu-db
  dnsNames:
    - "lamassu-db"
  secretName: lamassu-db-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: lamassu-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamassu-db-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:  100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lamassu-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  claimRef:
    namespace: default
    name: lamassu-db-pvc
  hostPath:
    path: "/data/lamassu-db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamassu-db-deployment
  namespace: default
  labels:
    app: lamassu-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamassu-db
  template:
    metadata:
      labels:
        app: lamassu-db
    spec:
      containers:
        - name: lamassu-db
          image: lamassuiot/lamassu-db:v1.0.6
          volumeMounts:
            - name: lamassu-db-pv
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
      restartPolicy: Always
      volumes:
        - name: lamassu-db-pv
          persistentVolumeClaim:
            claimName: lamassu-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lamassu-db
  namespace: default
spec:
  selector:
    app: lamassu-db
  type: ClusterIP
  ports:
  - name: lamassu-db
    port: 5432
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: lamassu-db-ingress
  namespace: default
  annotations: 
    cert-manager.io/issuer: "lamassu-ca-issuer"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - lamassu-db.dev.lamassu.io
    secretName: downstream-crt-secret
  rules:
  - host: lamassu-db.dev.lamassu.iov
    http: 
      paths:
      - pathType: Prefix
        path: /
        backend: 
          service: 
            name: "lamassu-db"
            port:
              number: 5432
