---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-cm
  namespace: {{.Release.Namespace}}
data:
  config.json: |
    {
      "datacenter": "lamassu-dc",
      "log_level": "INFO",
      "node_name": "consul-server",
      "server": true,
      "ui_config": {
          "enabled": true
      },
      "addresses": {
          "http": "0.0.0.0"
      },
      "ports": {
          "http": 8500
      },
      "http_config": {
          "response_headers": {
              "Access-Control-Allow-Origin": "*"
          }
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
  namespace: {{.Release.Namespace}}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: consul-deployment
  namespace: {{.Release.Namespace}}
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: {{.Values.image.consul}}
          volumeMounts:
            - name: consul-pv
              mountPath: /consul/data
            - name: consul-json-config
              mountPath: /consul/config/server.json
              subPath: config.json
          ports:
            - containerPort: 8500
          command: ["consul", "agent", "-server", "-bootstrap-expect=1", "-data-dir", "/consul/data", "-config-dir", "/consul/config"]
      restartPolicy: Always
      volumes:
        - name: consul-pv
          persistentVolumeClaim:
            claimName: consul-pvc
        - name: consul-json-config
          configMap:  
            name: consul-cm
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: consul
  type: ClusterIP
  ports:
  - name: http
    port: 8500
    targetPort: 8500
    protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: consul-vs
  namespace: {{.Release.Namespace}}
spec:
  hosts:
  - consul.{{.Values.domain}}
  gateways:
  - lamassu-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8500
        host: consul