---
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: rabbitmq-deployment
  namespace: {{.Release.Namespace}}
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{.Values.image.rabbitmq}}
          ports:
            - containerPort: 5671
            - containerPort: 15671
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
  - name: amqp
    port: 5671
    targetPort: 5671
  - name: https
    port: 15671
    targetPort: 15671
    protocol: TCP